/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/material/onlyRings-1.glb 
*/

import { useMemo, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { MeshStandardMaterial, type Mesh } from "three";
import {
  applyRingEffect,
  type RingEffectId,
  type RingShader,
  type RingShaderTimeRef,
} from "../shaders/ringEffects";

type Vec3 = [number, number, number];

type RingNodes = {
  rings1: Mesh;
  rings2: Mesh;
  rings3: Mesh;
};

type RingGLTF = {
  nodes: RingNodes;
};

interface ModelProps {
  scale?: Vec3;
  position?: Vec3;
  effect?: RingEffectId;
}

export function Model(props: ModelProps) {
  const modelScale: Vec3 = props.scale ?? [1, 1, 1];
  const modelPosition: Vec3 = props.position ?? [0, 0, 0];
  const ringEffect: RingEffectId = props.effect ?? "iridescentOilFilm";
  const { nodes } = useGLTF("/material/onlyRings-1.glb") as unknown as RingGLTF;
  const shaderRef = useRef<RingShaderTimeRef | null>(null);

  // One shared material keeps the effect synchronized across all 3 rings.
  const customMaterial = useMemo(() => {
    const material = new MeshStandardMaterial({
      color: 0x06080d,
      roughness: 0.3,
      metalness: 0.9,
      emissive: 0x06142b,
      emissiveIntensity: 0.35,
      transparent: true,
    });

    material.onBeforeCompile = (shader: RingShader) => {
      applyRingEffect(shader, ringEffect, shaderRef);
    };

    // Without a per-effect key, Three.js may reuse the first compiled shader.
    material.customProgramCacheKey = () => `rings-${ringEffect}`;
    material.needsUpdate = true;

    return material;
  }, [ringEffect]);

  // Animate shader uniforms
  useFrame((_, delta) => {
    if (shaderRef.current) {
      shaderRef.current.uniforms.uTime.value += delta;
    }
  });

  return (
    <>
      <mesh
        geometry={nodes.rings3.geometry}
        material={customMaterial}
        position={[modelPosition[0], modelPosition[1] + 0.22, modelPosition[2]]}
        scale={modelScale}
      />
      <mesh
        geometry={nodes.rings2.geometry}
        material={customMaterial}
        position={[modelPosition[0], modelPosition[1] - 0.22, modelPosition[2]]}
        scale={modelScale}
      />
      <mesh
        geometry={nodes.rings1.geometry}
        material={customMaterial}
        position={modelPosition}
        scale={modelScale}
      />
    </>
  );
}

useGLTF.preload("/material/onlyRings-1.glb");
